# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'oneSignalNotificationExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  # Pods for oneSignalNotificationExtension

end

target 'push notifications' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

  # Pods for push notifications

end
